export const AdErrors = {
  NOT_FB_INSTANT: 'NOT_FB_INSTANT',
  OFFLINE: 'OFFLINE',
  AD_NOT_READY: 'AD_NOT_READY',
  LOAD_FAILED: 'LOAD_FAILED',
  SHOW_FAILED: 'SHOW_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVER_ERROR: 'SERVER_ERROR',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_PLACEMENT: 'INVALID_PLACEMENT',
  COOLDOWN_ACTIVE: 'COOLDOWN_ACTIVE',
  DAILY_LIMIT: 'DAILY_LIMIT',
  DUPLICATE_REWARD: 'DUPLICATE_REWARD'
};
