export const REWARDED_TAROT_UNLOCK_ID = 'PASTE_REWARDED_ID_HERE';
export const INTERSTITIAL_TAROT_ID = 'PASTE_INTERSTITIAL_ID_HERE';
export const INTERSTITIAL_WHEEL_ID = 'PASTE_INTERSTITIAL_ID_HERE';
export const INTERSTITIAL_PANDIT_ID = 'PASTE_INTERSTITIAL_ID_HERE';
export const BANNER_HOME_ID = 'PASTE_BANNER_ID_HERE';
export const BANNER_TAROT_ID = 'PASTE_BANNER_ID_HERE';
