export const tarotData = [
  {
    id: 1,
    name: "The Sun",
    image: "☀️",
    love_en: "A period of joy and radiant energy in your relationship. Truth shines through.",
    career_en: "Success and recognition are coming your way. Your path is illuminated.",
    health_en: "Vitality is at its peak. Energy levels are high and healing is occurring.",
    love_hi: "आपके रिश्ते में खुशी और उज्ज्वल ऊर्जा का समय है। सच्चाई सामने आएगी।",
    career_hi: "सफलता और पहचान आपके रास्ते में आ रही है। आपका मार्ग प्रशस्त है।",
    health_hi: "जीवनशक्ति अपने चरम पर है। ऊर्जा का स्तर ऊंचा है और स्वास्थ्य में सुधार हो रहा है।",
  },
  {
    id: 2,
    name: "The Moon",
    image: "🌙",
    love_en: "Intuition is key. Not everything is as it seems in your romantic life.",
    career_en: "Hidden factors may be at play. Trust your gut feeling about a deal.",
    health_en: "Pay attention to your mental peace and dreams. Listen to your body.",
    love_hi: "अंतर्ज्ञान महत्वपूर्ण है। आपके रोमांटिक जीवन में सब कुछ वैसा नहीं है जैसा दिखता है।",
    career_hi: "छिपे हुए कारक खेल में हो सकते हैं। किसी सौदे के बारे में अपने अंतर्मन पर भरोसा करें।",
    health_hi: "अपनी मानसिक शांति और सपनों पर ध्यान दें। अपने शरीर की सुनें।",
  },
  {
    id: 3,
    name: "The Star",
    image: "⭐",
    love_en: "Hope and renewal. A deep spiritual connection is forming or healing.",
    career_en: "Inspiration is flowing. Your long-term goals are aligning with the universe.",
    health_en: "Peace and rejuvenation. A great time for detox and spiritual healing.",
    love_hi: "आशा और नवीनीकरण। एक गहरा आध्यात्मिक संबंध बन रहा है या सुधर रहा है।",
    career_hi: "प्रेरणा प्रवाहित हो रही है। आपके दीर्घकालिक लक्ष्य ब्रह्मांड के साथ संरेखित हो रहे हैं।",
    health_hi: "शांति और कायाकल्प। डिटॉक्स और आध्यात्मिक उपचार के लिए एक अच्छा समय है।",
  },
  {
    id: 4,
    name: "The Lovers",
    image: "💖",
    love_en: "A significant choice or partnership defines your path. Harmony is essential.",
    career_en: "Alignment of values in a professional partnership leads to great success.",
    health_en: "Balance is needed between mind and body. Choose healthy habits.",
    love_hi: "एक महत्वपूर्ण विकल्प या साझेदारी आपके पथ को परिभाषित करती है। सद्भाव आवश्यक है।",
    career_hi: "एक पेशेवर साझेदारी में मूल्यों का तालमेल बड़ी सफलता की ओर ले जाता है।",
    health_hi: "मन और शरीर के बीच संतुलन की आवश्यकता है। स्वस्थ आदतों को चुनें।",
  },
  {
    id: 5,
    name: "The Wheel of Fortune",
    image: "🎡",
    love_en: "Changes are coming. Destiny is moving in your favor; stay adaptable.",
    career_en: "A sudden shift in luck. Be ready to seize an unexpected opportunity.",
    health_en: "Health cycles are turning. Focus on maintaining a consistent routine.",
    love_hi: "बदलाव आ रहे हैं। भाग्य आपके पक्ष में चल रहा है; अनुकूल बने रहें।",
    career_hi: "किस्मत में अचानक बदलाव। एक अप्रत्याशित अवसर का लाभ उठाने के लिए तैयार रहें।",
    health_hi: "स्वास्थ्य चक्र घूम रहे हैं। एक सुसंगत दिनचर्या बनाए रखने पर ध्यान दें।",
  }
];
