export const ProductIds = {
  PREMIUM_SEEKER: 'premium_seeker_status'
};

export const PaymentErrors = {
  NOT_SUPPORTED: 'PAYMENTS_NOT_SUPPORTED',
  INITIALIZATION_FAILED: 'PAYMENTS_INITIALIZATION_FAILED',
  USER_CANCELLED: 'USER_INPUT_CANCELLED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN: 'UNKNOWN_PAYMENT_ERROR',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED'
};
